name: 🤳 🪴 AR Button

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 📦 Set up node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: 💿 Install dependencies
        run: |
          npm install yarn
          yarn install --pure-lockfile

      - name: 🏗️ Build
        run:  yarn build:dev